#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

const configs = new Map([
  [ 'bash', `${process.env.HOME}/.bashrc` ],
  [ 'zsh' , `${process.env.HOME}/.zshrc`  ],
  [ 'fish', `${process.env.HOME}/.config/fish/config.fish` ],
]);

console.log(chalk.cyan('Ianstalling robbyrussell theme...'));

const shell  = path.basename(process.env.SHELL);
const cwd    = process.cwd();
const config = configs.get(shell);

console.log(chalk.cyan('Current shell:'), shell);
console.log(chalk.cyan('Working directory:'), cwd);
console.log(chalk.cyan('Shell\'s config stored at:'), config);

try {
  console.log(chalk.cyan(`Appending to ${config}...`));

  fs.appendFileSync(config, `
### GENERATED BY ROBBYRUSSELL
. ${cwd}/adapter.${shell}
### GENERATED BY ROBBYRUSSELL
`, 'utf8');

  console.log(chalk.green('Done! Please, reload your terminal.'));
} catch (e) {
  console.log(chalk.red(`Something went wrong!`));
  console.log(chalk.red(`Don't panic! Report an issue to:`));
  console.log(chalk.red(`\n\thttps://github.com/denysdovhan/robbyrussell/issues/new`));
  throw e;
}
