#!/usr/bin/env node

const robbyrussell = require('.');
const deepAssign = require('deep-assign');
const defaultConfig = require('./config');
const { loadConfig, processPrint } = require('./utils/common');

const configPath = `${process.env.HOME}/.prompt-config.js`

const config = deepAssign({}, defaultConfig, loadConfig(configPath), {
  code: Number(process.argv[2]),
  cwd: process.cwd(),
})

if (config.async) {
  robbyrussell.promptAsync(config)
    .then(output => processPrint(output))
    .catch(reason => processPrint(reason));
} else {
  const output = robbyrussell.prompt(config);
  processPrint(output);
}
