#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

const configs = new Map([
  [ 'bash', `${process.env.HOME}/.bashrc` ],
  [ 'zsh' , `${process.env.HOME}/.zshrc`  ],
  [ 'fish', `${process.env.HOME}/.config/fish/config.fish` ],
]);

console.log(chalk.cyan('Uninstalling robbyrussell theme...'));

const shell  = path.basename(process.env.SHELL);
const config = configs.get(shell);

console.log(chalk.cyan('Current shell:'), shell);
console.log(chalk.cyan('Shell\'s config stored at:'), config);

const regexp = /### GENERATED BY ROBBYRUSSELL(.|\n)*### GENERATED BY ROBBYRUSSELL/g;

try {
  console.log(chalk.cyan(`Reading ${config}...`));
  const content = fs.readFileSync(config, 'utf8');
  console.log(chalk.cyan(`Updating ${config}...`));
  // TODO: Check if theme is present in shell config
  fs.writeFileSync(config, content.replace(regexp, ''), 'utf8');
  console.log(chalk.green('Done! Please, reload your terminal.'))
} catch (e) {
  console.log(chalk.red(`Something went wrong!`));
  console.log(chalk.red(`Don't panic! Report an issue to:`));
  console.log(chalk.red(`\n\thttps://github.com/denysdovhan/robbyrussell/issues/new`));
  throw e;
}
